languageCode = "en-us"
title = "Maheswaran Moothiringode"
baseurl = "http://maheswaranm.com/"
theme = ""

[params]
  name = "Maheswaran Moothiringode"
  description = "Maker  of  Software"
  copyright = "Maheswaran Moothiringode"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/maheswaranm"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/maheswaranm/"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://linkedin.com/in/maheswaranm/"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:talk@maheswaranm.com"


[[params.links]]
  name = "Blog"
  icon = "pencil-square-o"
  link = "https://blog.maheswaranm.com"

[[params.links]]
  name = "Projects"
  icon = "gears"
  link = "https://projects.maheswaranm.com"